(function(){function TiledGalleryCollection(){this.galleries=[];this.findAndSetupNewGalleries();}
TiledGalleryCollection.prototype.findAndSetupNewGalleries=function(){var self=this;var unresizedGalleries=document.querySelectorAll('.tiled-gallery.tiled-gallery-unresized');Array.prototype.forEach.call(unresizedGalleries,function(el){self.galleries.push(new TiledGallery(el));});};TiledGalleryCollection.prototype.resizeAll=function(){Array.prototype.forEach.call(this.galleries,function(gallery){gallery.resize();});};function TiledGallery(galleryElem){this.gallery=galleryElem;this.addCaptionEvents();this.resize();this.gallery.classList.remove('tiled-gallery-unresized');}
TiledGallery.prototype.resizeableElementsSelector='.gallery-row, .gallery-group, .tiled-gallery-item img';TiledGallery.prototype.addCaptionEvents=function(){var galleryCaptions=this.gallery.querySelectorAll('.tiled-gallery-caption');Array.prototype.forEach.call(galleryCaptions,function(el){el.style.display='none';});var mouseHoverHandler=function(e){var itemEl=e.target.closest('.tiled-gallery-item');var displayValue='mouseover'===e.type?'block':'none';if(itemEl){var itemCaption=itemEl.querySelector('.tiled-gallery-caption');if(itemCaption){itemCaption.style.display=displayValue;}}};this.gallery.addEventListener('mouseover',mouseHoverHandler);this.gallery.addEventListener('mouseout',mouseHoverHandler);};TiledGallery.prototype.getExtraDimension=function(el,attribute,mode){if(mode==='horizontal'){var left=attribute==='border'?'borderLeftWidth':attribute+'Left';var right=attribute==='border'?'borderRightWidth':attribute+'Right';return(parseInt(el.style[left],10)||0)+(parseInt(el.style[right],10)||0);}else if(mode==='vertical'){var top=attribute==='border'?'borderTopWidth':attribute+'Top';var bottom=attribute==='border'?'borderBottomWidth':attribute+'Bottom';return(parseInt(el.style[top],10)||0)+(parseInt(el.style[bottom],10)||0);}else{return 0;}};TiledGallery.prototype.resize=function(){var originalWidth=parseInt(this.gallery.dataset.originalWidth,10);var currentWidth=parseFloat(getComputedStyle(this.gallery.parentNode,null).width.replace('px',''));var resizeRatio=Math.min(1,currentWidth/originalWidth);var self=this;var resizableElements=this.gallery.querySelectorAll(this.resizeableElementsSelector);Array.prototype.forEach.call(resizableElements,function(el){var marginWidth=self.getExtraDimension(el,'margin','horizontal');var marginHeight=self.getExtraDimension(el,'margin','vertical');var paddingWidth=self.getExtraDimension(el,'padding','horizontal');var paddingHeight=self.getExtraDimension(el,'padding','vertical');var borderWidth=self.getExtraDimension(el,'border','horizontal');var borderHeight=self.getExtraDimension(el,'border','vertical');var outerWidth=parseInt(el.dataset.originalWidth,10)+paddingWidth+borderWidth+marginWidth;var outerHeight=parseInt(el.dataset.originalHeight,10)+paddingHeight+borderHeight+marginHeight;el.style.width=Math.floor(resizeRatio*outerWidth)-marginWidth+'px';el.style.height=Math.floor(resizeRatio*outerHeight)-marginHeight+'px';});};var requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;function attachResizeInAnimationFrames(tiledGalleries){var resizing=false;var resizeTimeout=null;function handleFrame(){tiledGalleries.resizeAll();if(resizing){requestAnimationFrame(handleFrame);}}
window.addEventListener('resize',function(){clearTimeout(resizeTimeout);if(!resizing){requestAnimationFrame(handleFrame);}
resizing=true;resizeTimeout=setTimeout(function(){resizing=false;},15);});}
function attachPlainResize(tiledGalleries){window.addEventListener('resize',function(){tiledGalleries.resizeAll();});}
function ready(fn){if(document.readyState!=='loading'){fn();}else{document.addEventListener('DOMContentLoaded',fn);}}
ready(function(){var tiledGalleries=new TiledGalleryCollection();document.body.addEventListener('is.post-load',function(){tiledGalleries.findAndSetupNewGalleries();});if(typeof jQuery==='function'){jQuery(document).on('page-rendered.wpcom-newdash',function(){tiledGalleries.findAndSetupNewGalleries();});}
if(window.chrome&&requestAnimationFrame){attachResizeInAnimationFrames(tiledGalleries);}else{attachPlainResize(tiledGalleries);}
if('undefined'!==typeof wp&&wp.customize&&wp.customize.selectiveRefresh){wp.customize.selectiveRefresh.bind('partial-content-rendered',function(placement){if(wp.isJetpackWidgetPlaced(placement,'gallery')){tiledGalleries.findAndSetupNewGalleries();}});}});})();