(function(){var Scroller,ajaxurl,stats,type,text,totop,loading_text;var isIE=-1!=navigator.userAgent.search('MSIE');if(isIE){var IEVersion=navigator.userAgent.match(/MSIE\s?(\d+)\.?\d*;/);IEVersion=parseInt(IEVersion[1]);}
if('https:'==document.location.protocol){infiniteScroll.settings.ajaxurl=infiniteScroll.settings.ajaxurl.replace('http://','https://');}
Scroller=function(settings){var self=this;this.id=settings.id;this.body=document.body;this.window=window;this.element=document.getElementById(settings.id);this.wrapperClass=settings.wrapper_class;this.ready=true;this.disabled=false;this.page=1;this.offset=settings.offset;this.currentday=settings.currentday;this.order=settings.order;this.throttle=false;this.click_handle=settings.click_handle;this.google_analytics=settings.google_analytics;this.history=settings.history;this.origURL=window.location.href;this.handle=document.createElement('div');this.handle.setAttribute('id','infinite-handle');this.handle.innerHTML='<span><button>'+text.replace('\\','')+'</button></span>';this.footer={el:document.getElementById('infinite-footer'),wrap:settings.footer,};this.checkViewportOnLoadBound=self.checkViewportOnLoad.bind(this);this.wpMediaelement=null;if(type=='scroll'){this.window.addEventListener('scroll',function(){self.throttle=true;});self.gotop();setInterval(function(){if(self.throttle){self.throttle=false;self.thefooter();self.refresh();self.determineURL();}},250);self.ensureFilledViewport();this.body.addEventListener('is.post-load',self.checkViewportOnLoadBound);}else if(type=='click'){if(this.click_handle){this.element.appendChild(this.handle);}
this.handle.addEventListener('click',function(){if(self.click_handle){self.handle.parentNode.removeChild(self.handle);}
self.refresh();});}
this.body.addEventListener('is.post-load',self.initializeMejs);};Scroller.prototype.getScrollTop=function(){return window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0;};Scroller.prototype.extend=function(out){out=out||{};for(var i=1;i<arguments.length;i++){if(!arguments[i]){continue;}
for(var key in arguments[i]){if(arguments[i].hasOwnProperty(key)){out[key]=arguments[i][key];}}}
return out;};Scroller.prototype.check=function(){var wrapperMeasurements=this.measure(this.element,[this.wrapperClass]);return wrapperMeasurements.bottom<2*this.window.innerHeight;};Scroller.prototype.render=function(response){var childrenToAppend=Array.prototype.slice.call(response.fragment.childNodes);this.body.classList.add('infinity-success');while(childrenToAppend.length>0){var currentNode=childrenToAppend.shift();this.element.appendChild(currentNode);}
this.trigger(this.body,'is.post-load',{jqueryEventName:'post-load',data:response,});this.ready=true;};Scroller.prototype.query=function(){return{page:this.page+this.offset,currentday:this.currentday,order:this.order,scripts:window.infiniteScroll.settings.scripts,styles:window.infiniteScroll.settings.styles,query_args:window.infiniteScroll.settings.query_args,query_before:window.infiniteScroll.settings.query_before,last_post_date:window.infiniteScroll.settings.last_post_date,};};Scroller.prototype.animate=function(cb,duration){var start=performance.now();requestAnimationFrame(function animate(time){var timeFraction=Math.min(1,(time-start)/duration);cb(timeFraction);if(timeFraction<1){requestAnimationFrame(animate);}});};Scroller.prototype.gotop=function(){var blog=document.getElementById('infinity-blog-title');var self=this;if(!blog){return;}
blog.setAttribute('title',totop);blog.addEventListener('click',function(e){var sourceScroll=self.window.pageYOffset;e.preventDefault();self.animate(function(progress){var currentScroll=sourceScroll-sourceScroll*progress;document.documentElement.scrollTop=document.body.scrollTop=currentScroll;},200);});};Scroller.prototype.thefooter=function(){var self=this,pageWrapper,footerContainer,width,sourceBottom,targetBottom,footerEnabled=this.footer&&this.footer.el;if(!footerEnabled){return;}
if('string'===typeof this.footer.wrap){try{pageWrapper=document.getElementById(this.footer.wrap);width=pageWrapper.getBoundingClientRect();width=width.width;}catch(err){width=0;}
if(width>479){footerContainer=this.footer.el.querySelector('.container');if(footerContainer){footerContainer.style.width=width+'px';}}}
sourceBottom=parseInt(self.footer.el.style.bottom||-50,10);targetBottom=this.window.pageYOffset>=350?0:-50;if(sourceBottom!==targetBottom){self.animate(function(progress){var currentBottom=sourceBottom+(targetBottom-sourceBottom)*progress;self.footer.el.style.bottom=currentBottom+'px';if(1===progress){sourceBottom=targetBottom;}},200);}};Scroller.prototype.urlEncodeJSON=function(obj,prefix){var params=[],encodedKey,newPrefix;for(var key in obj){encodedKey=encodeURIComponent(key);newPrefix=prefix?prefix+'['+encodedKey+']':encodedKey;if('object'===typeof obj[key]){if(!Array.isArray(obj[key])||obj[key].length>0){params.push(this.urlEncodeJSON(obj[key],newPrefix));}else{params.push(newPrefix+'[]=');}}else{params.push(newPrefix+'='+encodeURIComponent(obj[key]));}}
return params.join('&');};Scroller.prototype.refresh=function(){var self=this,query,xhr,loader,customized;if(this.disabled||!this.ready||!this.check()){return;}
this.ready=false;if(this.click_handle){if(!loader){document.getElementById('infinite-aria').textContent=loading_text;loader=document.createElement('div');loader.classList.add('infinite-loader');loader.setAttribute('role','progress');loader.innerHTML='<div class="spinner"><div class="spinner-inner"><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div></div></div>';}
this.element.appendChild(loader);}
query=self.extend({action:'infinite_scroll',},this.query());if('undefined'!==typeof wp&&wp.customize&&wp.customize.settings.theme){customized={};query.wp_customize='on';query.theme=wp.customize.settings.theme.stylesheet;wp.customize.each(function(setting){if(setting._dirty){customized[setting.id]=setting();}});query.customized=JSON.stringify(customized);query.nonce=wp.customize.settings.nonce.preview;}
xhr=new XMLHttpRequest();xhr.open('POST',infiniteScroll.settings.ajaxurl,true);xhr.setRequestHeader('X-Requested-With','XMLHttpRequest');xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded; charset=UTF-8');xhr.send(self.urlEncodeJSON(query));xhr.onerror=function(){if(self.click_handle){loader.parentNode.removeChild(loader);}
self.ready=true;};xhr.onload=function(){var response=JSON.parse(xhr.responseText),httpCheck=xhr.status>=200&&xhr.status<300,responseCheck='undefined'!==typeof response.html;if(!response||!httpCheck||!responseCheck){if(self.click_handle){loader.parentNode.removeChild(loader);}
return;}
if(self.click_handle){loader.parentNode.removeChild(loader);}
if(response.scripts&&Array.isArray(response.scripts)){response.scripts.forEach(function(item){var elementToAppendTo=item.footer?'body':'head';window.infiniteScroll.settings.scripts.push(item.handle);if(item.extra_data){self.appendInlineScript(item.extra_data,elementToAppendTo);}
if(item.before_handle){self.appendInlineScript(item.before_handle,elementToAppendTo);}
var script=document.createElement('script');script.type='text/javascript';script.src=item.src;script.id=item.handle;script.async=false;if(item.after_handle){script.onload=function(){self.appendInlineScript(item.after_handle,elementToAppendTo);};}
if('wp-mediaelement'===item.handle){self.body.removeEventListener('is.post-load',self.initializeMejs);}
if('wp-mediaelement'===item.handle&&'undefined'===typeof mejs){self.wpMediaelement={};self.wpMediaelement.tag=script;self.wpMediaelement.element=elementToAppendTo;setTimeout(self.maybeLoadMejs.bind(self),250);}else{document.getElementsByTagName(elementToAppendTo)[0].appendChild(script);}});}
if(response.styles&&Array.isArray(response.styles)){response.styles.forEach(function(item){window.infiniteScroll.settings.styles.push(item.handle);var style=document.createElement('link');style.rel='stylesheet';style.href=item.src;style.id=item.handle+'-css';if(item.conditional&&(!isIE||!eval(item.conditional.replace(/%ver/g,IEVersion)))){style=false;}
if(style){document.getElementsByTagName('head')[0].appendChild(style);}});}
response.fragment=document.createElement('div');response.fragment.innerHTML=response.html;self.page++;if(stats){new Image().src=document.location.protocol+
'//pixel.wp.com/g.gif?'+
stats+
'&post=0&baba='+
Math.random();}
if('object'===typeof response.postflair&&'object'===typeof WPCOM_sharing_counts){WPCOM_sharing_counts=self.extend(WPCOM_sharing_counts,response.postflair);}
self.render.call(self,response);if(type=='click'){if(infiniteScroll.settings.wrapper){document.querySelector('#infinite-view-'+(self.page+self.offset-1)+' a:first-of-type').focus({preventScroll:true,});}
if(response.lastbatch){if(self.click_handle){self.body.classList.add('infinity-end');self.body.classList.remove('infinity-success');}else{self.trigger(this.body,'infinite-scroll-posts-end');}}else{if(self.click_handle){self.element.appendChild(self.handle);}else{self.trigger(this.body,'infinite-scroll-posts-more');}}}else if(response.lastbatch){self.disabled=true;self.body.classList.add('infinity-end');self.body.classList.remove('infinity-success');}
if(response.currentday){self.currentday=response.currentday;}
if(self.google_analytics){var ga_url=self.history.path.replace(/%d/,self.page);if('object'===typeof _gaq){_gaq.push(['_trackPageview',ga_url]);}
if('function'===typeof ga){ga('send','pageview',ga_url);}}};return xhr;};Scroller.prototype.appendInlineScript=function(script,parentTag){var element=document.createElement('script'),scriptContent=document.createTextNode('//<![CDATA[ \n'+script+'\n//]]>');element.type='text/javascript';element.appendChild(scriptContent);document.getElementsByTagName(parentTag)[0].appendChild(element);};Scroller.prototype.maybeLoadMejs=function(){if(null===this.wpMediaelement){return;}
if('undefined'===typeof mejs){setTimeout(this.maybeLoadMejs.bind(this),250);}else{document.getElementsByTagName(this.wpMediaelement.element)[0].appendChild(this.wpMediaelement.tag);this.wpMediaelement=null;this.body.addEventListener('is.post-load',this.initializeMejs);}};Scroller.prototype.initializeMejs=function(e){if(!e.detail||!e.detail.html||(-1===e.detail.html.indexOf('wp-audio-shortcode')&&-1===e.detail.html.indexOf('wp-video-shortcode'))){return;}
if('undefined'===typeof mejs){return;}
var settings={};var audioVideoElements;if(typeof _wpmejsSettings!=='undefined'){settings.pluginPath=_wpmejsSettings.pluginPath;}
settings.success=function(mejs){var autoplay=mejs.attributes.autoplay&&'false'!==mejs.attributes.autoplay;if('flash'===mejs.pluginType&&autoplay){mejs.addEventListener('canplay',function(){mejs.play();},false);}};audioVideoElements=document.querySelectorAll('.wp-audio-shortcode, .wp-video-shortcode');audioVideoElements=Array.prototype.slice.call(audioVideoElements);audioVideoElements=audioVideoElements.filter(function(el){while(el.parentNode){if(el.classList.contains('mejs-container')){return false;}
el=el.parentNode;}
return true;});for(var i=0;i<audioVideoElements.length;i++){new MediaElementPlayer(audioVideoElements[i],settings);}};Scroller.prototype.measure=function(element,expandClasses){expandClasses=expandClasses||[];var childrenToTest=Array.prototype.slice.call(element.children);var currentChild,minTop=Number.MAX_VALUE,maxBottom=0,currentChildRect,i;while(childrenToTest.length>0){currentChild=childrenToTest.shift();for(i=0;i<expandClasses.length;i++){if(currentChild.classList.contains(expandClasses[i])){childrenToTest=childrenToTest.concat(Array.prototype.slice.call(currentChild.children));break;}}
currentChildRect=currentChild.getBoundingClientRect();minTop=Math.min(minTop,currentChildRect.top);maxBottom=Math.max(maxBottom,currentChildRect.bottom);}
var viewportMiddle=Math.round(window.innerHeight/2);var isActive=minTop<=viewportMiddle&&maxBottom>=viewportMiddle;var factor=(Math.min(maxBottom,viewportMiddle)-Math.max(minTop,0))/viewportMiddle;return{top:minTop,bottom:maxBottom,height:maxBottom-minTop,factor:factor,isActive:isActive,};};Scroller.prototype.ensureFilledViewport=function(){var self=this,windowHeight=self.window.innerHeight,wrapperMeasurements=self.measure(self.element,[self.wrapperClass]);self.body.removeEventListener('is.post-load',self.checkViewportOnLoadBound);if(wrapperMeasurements.bottom<windowHeight){self.ready=true;self.refresh();}};Scroller.prototype.checkViewportOnLoad=function(){this.ensureFilledViewport();};function fullscreenState(){return document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement?1:0;}
var previousFullScrenState=fullscreenState();Scroller.prototype.determineURL=function(){var self=this,pageNum=-1,currentFullScreenState=fullscreenState(),wrapperEls,maxFactor=0;if(previousFullScrenState^currentFullScreenState){previousFullScrenState=currentFullScreenState;return;}
previousFullScrenState=currentFullScreenState;wrapperEls=document.querySelectorAll('.'+self.wrapperClass);for(var i=0;i<wrapperEls.length;i++){var setMeasurements=self.measure(wrapperEls[i]);if(setMeasurements.isActive){pageNum=parseInt(wrapperEls[i].dataset.pageNum,10);break;}
if(setMeasurements.factor>maxFactor){pageNum=parseInt(wrapperEls[i].dataset.pageNum,10);maxFactor=setMeasurements.factor;}}
self.updateURL(pageNum);};Scroller.prototype.updateURL=function(page){if(!window.history.pushState){return;}
var self=this,pageSlug=self.origURL;if(-1!==page){pageSlug=window.location.protocol+
'//'+
self.history.host+
self.history.path.replace(/%d/,page)+
self.history.parameters;}
if(window.location.href!=pageSlug){history.pushState(null,null,pageSlug);}};Scroller.prototype.pause=function(){this.disabled=true;};Scroller.prototype.resume=function(){this.disabled=false;};Scroller.prototype.trigger=function(el,eventName,opts){opts=opts||{};if(opts.jqueryEventName&&'undefined'!==typeof jQuery){jQuery(el).trigger(opts.jqueryEventName,opts.data||null);}
var e;try{e=new CustomEvent(eventName,{bubbles:true,cancelable:true,detail:opts.data||null,});}catch(err){e=document.createEvent('CustomEvent');e.initCustomEvent(eventName,true,true,opts.data||null);}
el.dispatchEvent(e);};var jetpackInfinityModule=function(){var bodyClasses=infiniteScroll.settings.body_class.split(' ');if('object'!==typeof infiniteScroll){return;}
bodyClasses.forEach(function(className){if(className){document.body.classList.add(className);}});ajaxurl=infiniteScroll.settings.ajaxurl;stats=infiniteScroll.settings.stats;type=infiniteScroll.settings.type;text=infiniteScroll.settings.text;totop=infiniteScroll.settings.totop;loading_text=infiniteScroll.settings.loading_text;infiniteScroll.scroller=new Scroller(infiniteScroll.settings);if(type=='click'){var timer=null;window.addEventListener('scroll',function(){if(timer){return;}
timer=setTimeout(function(){infiniteScroll.scroller.determineURL();timer=null;},250);});}};if(document.readyState==='interactive'||document.readyState==='complete'){jetpackInfinityModule();}else{document.addEventListener('DOMContentLoaded',jetpackInfinityModule);}})();